### PR TITLE
CPU hours log

### PR DESCRIPTION
**Pull request by kate-v-stepanova**
quota_log.py script runs projinfo command and saves results in the database

### CODE REVIEW

**Comment by ewels** [comment]
Cool! Only comment about this is about how it saves to the database - I think I'm correct in saying that this will create two separate objects, with different keys? It might be nicer to save a single document with all keys. Could do this by getting both functions to return the dict, then merging them and saving that to the database.

Only other thing is that it would be nice to use database details from a log file instead of having to specify them on the command line (and so making them public to everyone with access to genstat through the cronjobs page). @Galithil - do you have any suggestions for which config file to get this from? Better still, which chunk of code to copy and paste for this?

**Comment by senthil10** [comment]
Nice work @kate-v-stepanova :) I too just have the same comments as @ewels  and as far the config file, you can use `/home/funk_001/.ngi_config/statusdb.yaml` (as this script is **UPPMAX** particular)

**Comment by kate-v-stepanova** [comment]
@ewels - yes, you're right, it's better to merge objects and save them only once
@senthil10 - perfect, i'll use this one :)

**Comment by Galithil** [comment]
Try to avoid having code in the if __name__ == "__main__" : 
I usually simply have the args parsing and a main(args), where I start doing the actual work, I don't really like having half of the code down there, because I can't read, for instance disk_quota before reading what's at the end of the file.

Also, what happens if there is already a document about a given project quota and you run the script ? Does it create another document ? Is that what is intended ? 

Same comment about having to pass user/pw via the command line.

**Comment by ewels** [comment]
@Galithil - interesting, I always do the `name == "main"` thing (as instructed when I started). I thought it was good practice as then your code can be imported and the functions run by another package.. Eller hur?

It should create a new document every time, then we get a time series that can be plotted.

**Comment by Galithil** [comment]
You should have the name == main thing, but the code inside should be as minimal as possible.The more code you have in it, the less you can use it as a module.

**Comment by pekrau** [comment]
Yes, @Galithil is quite right. The name == '__main__' part should ideally contain only calls to procedures defined above in the script. It makes the logic clearer, and also makes the module more reusable.

**Comment by ewels** [comment]
Aha, gotcha - sorry I misread and thought you were suggesting to move the argparse stuff into the main function. Good, you got me worried there @Galithil :grinning:

**Comment by pekrau** [comment]
I looked at the code diff right now, and it looked fine to me. The argparse stuff can go into the name=='main' section, unless it is very long.

**Comment by ewels** [comment]
I suspect that @Galithil is referring to this little chunk:

```python
# create db instance
if args.server == "":
    db = None
else:
    couch = couchdb.Server(args.server)
    db = couch[args.db]
```

**Comment by pekrau** [comment]
OK. Hmm, I think that code chunk is reasonable. Although the docstrings of the __procedures__ (not just module) should be explicit about it, I think the logic is fairly clear. And the modularity is not compromised by this particular code chunk.

Opinion: The procedure definitions should be like `def disk_quota(db=None):` which makes explicit that the db argument can be omitted.

**Comment by kate-v-stepanova** [comment]
Ok, new update -> 
1. the __main__ function now only contains calls of other functions
2. about the code above - it is moved to a new method 'save_results'
3. DB credentials are now loaded from config file

**Comment by Galithil** [comment]
Nice !

our ex-resident coders used to  advise to use
with open(filename) as f :
  <rest of the code>

instead of open, because it saves you for having to explicitly call
filehandler.close() to make sure you closed the handler.

I don't have a preference, but please try to close every file you open as
soon as you don't need it again, or use the with statement.
Here is an exemple, in genomics status :
https://github.com/SciLifeLab/genomics-status/blob/master/status_app.py#L307

**Comment by kate-v-stepanova** [comment]
Wouldn't be the file anyway closed authomaitically? 
but ok - done

**Comment by Galithil** [comment]
The file is closed at the end of the script. In this case, there is not much time between the two, so it doesnt really matter, but if you end up working on an application that never stops, like genomics-status, you want to avoid having handlers being kept open. Same thing with multithreaded / parallellized apps. 

I can see that you're planning to add new documents in the uppmax db, and they seem to have three keys : project, cpu_hours, cpu_limit. 
The documents I can see in the db also have "time", is that something required to have the visualization ? 
Will the new documents, with only cpu information, interact with the quota view ?

**Comment by pekrau** [comment]
Yes, when execution moves out of the procedure, or rather, the scope of that file variable.

Using the "with" statement, one has complete control over when the close happens, without having to specify it: it happens when execution leaves the "with" block, even if an exception happens inside the block.

I use the "with" statement together with classes that implement the required enter and exit functions, for instance in database interactions.

**Comment by kate-v-stepanova** [comment]
@Galithil the documents are not gonna be new, I'll just add 2 new attributes to already existing objects. Time as far as I know is required - the plots on quota page display the usage over time, so it's one of parameters of y axis.

**Comment by ewels** [comment]
Nice, looks good!

**Pull request merged**
