### PR TITLE
Update email addresses in Lims monitor script

### PR DESCRIPTION
**Pull request by ewels**
Lots of people hardcoded into this script have left the NGI. Removed them, plus updated the main responsible from @Galithil to @parlundin 

Script should probably also be updated to add in new email addresses. Don't merge until we've looked into this.

### CODE REVIEW

**Review by alneberg — APPROVED** [review]
Look at all those pretty names!

**Comment by ewels** [comment]
ezgif-3-a058abd919c3

**Comment by alneberg** [comment]
So... most likely it is not this script that is running at all but instead this one: https://github.com/SciLifeLab/LIMS2DB/blob/master/scripts/mail_resp.py

That one doesn't have lists of email-adresses, so I don't know why some people don't get their emails.

**Comment by ewels** [comment]
🤦‍♂️ 

I'm not sure that anyone didn't get their emails. It was the outdated footer with Denis' email address that I originally set out to fix, then I saw the old email addresses at the top. So it's possible that it was already working properly for everyone.

**Comment by ewels** [comment]
...try again: https://github.com/SciLifeLab/LIMS2DB/pull/70

**Pull request merged**
