### PR TITLE
Better without it!!

### PR DESCRIPTION
**Pull request by senthil10**
This is creating conflict even the bcbio is installed, test and it works without mentioned it here.

### CODE REVIEW

**Comment by senthil10** [comment]
self merging as already discussed with @guillermo-carrasco  :+1:

**Comment by Galithil** [comment]
that's a bold change. I wonder wether PSUL will tolerate it

**Comment by guillermo-carrasco** [comment]
PSUL is usign `bcbio-nextgen`???

**Comment by Galithil** [comment]
A lot of import used to have it, mainly for the yaml conf parser. I did not
go through every import.

**Pull request merged**
